### ISSUE TITLE
Página de Manutenção

### ISSUE THREAD

**Issue by Phe0** [pi1-2019-1-whirl/front-end#5]
## Nome da Issue
Página de manutenção

## Descrição da Issue
Deve ser criada uma página de manutenção para que o usuário obtenha informações a respeito do funcionamento do produto

## Tarefas
 -  Dizer em tempo real se a turbina está girando ou não 
 - Construir um gráfico em tempo real com as informações da energia que está sendo gerada

**Comment by itallogravina** [comment]
nao sei como sera a entrada dos dados entao coloque algo simples
